version: '3'
services:
  backend:
    container_name: voyalert-backend
    image: ondrejnedoma/voyalert-backend:0.4.0
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - MONGODB_URL=mongo:27017/voyalert
    volumes:
      - ./firebase.json:/app/firebase.json
  mongo:
    container_name: voyalert-mongo
    image: mongo
    restart: always
