version: '3'
services:
  backend:
    container_name: voyalert-backend
    image: ondrejnedoma/voyalert-backend:0.4.0
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - MONGODB_URL=mongodb://mongo:27017/voyalert
    volumes:
      - ./firebase.json:/app/firebase.json
  mongo:
    container_name: voyalert-mongo
    image: mongo
    restart: always
  mongo-express:
    container_name: voyalert-mongo-express
    image: mongo-express
    restart: always
    ports:
      - 3001:3001
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/voyalert
