name: BUILD backend => Docker Hub

on:
  push:
    branches: ['master']
  workflow_dispatch:

jobs:
  evaluate-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.compare-versions.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Ger package.json version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: packages/backend
      - name: Compare package.json version and latest Docker Hub tag
        id: compare-versions
        env:
          PACKAGE_JSON_VERSION: ${{ steps.package-version.outputs.current-version }}
        run: |
          DOCKER_HUB_TAG=$(curl -s "https://hub.docker.com/v2/repositories/ondrejnedoma/voyalert-backend/tags/" | jq -r 'if has("results") and (.results | length > 0) then .results[0].name else "0" end')
          if [ "$DOCKER_HUB_TAG" == "$PACKAGE_JSON_VERSION" ]; then
            echo "Latest tag on Docker Hub matches version in package.json"
            echo "version=false" >> "$GITHUB_OUTPUT"
          else
            echo "Latest tag on Docker Hub does not match version in package.json, will build and push image to Docker Hub"
            echo "version=$PACKAGE_JSON_VERSION" >> "$GITHUB_OUTPUT"
          fi
  build:
    runs-on: ubuntu-latest
    needs: evaluate-version
    if: ${{ needs.evaluate-version.outputs.version != 'false' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ondrejnedoma/voyalert-backend:${{ needs.evaluate-version.outputs.version }}
