name: BUILD app

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Install dependencies
        run: |
          npm install
      - name: Build APK
        run: |
          cd packages/app/android
          chmod +x gradlew
          ./gradlew assembleRelease -Punsigned
      - name: Build AAB
        run: |
          cd packages/app/android
          chmod +x gradlew
          ./gradlew bundleRelease -Punsigned
